# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/himito/Dropbox/OSSIA_Project/Implementations/Timed_Automata/FPGA/Interactive_Scores/Interactive_Scores.cache/wt [current_project]
set_property parent.project_path /home/himito/Dropbox/OSSIA_Project/Implementations/Timed_Automata/FPGA/Interactive_Scores/Interactive_Scores.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.2 [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/himito/Dropbox/OSSIA_Project/Implementations/Timed_Automata/FPGA/Interactive_Scores/Interactive_Scores.srcs/sources_1/new/clock_divider.sv
  /home/himito/Dropbox/OSSIA_Project/Implementations/Timed_Automata/FPGA/Interactive_Scores/Interactive_Scores.srcs/sources_1/new/rigid_ta.sv
  /home/himito/Dropbox/OSSIA_Project/Implementations/Timed_Automata/FPGA/Interactive_Scores/Interactive_Scores.srcs/sources_1/new/clock_ta.sv
  /home/himito/Dropbox/OSSIA_Project/Implementations/Timed_Automata/FPGA/Interactive_Scores/Interactive_Scores.srcs/sources_1/new/interactive_score.sv
}
catch { write_hwdef -file interactive_score.hwdef }
synth_design -top interactive_score -part xc7z020clg484-1
write_checkpoint interactive_score.dcp
catch { report_utilization -file interactive_score_utilization_synth.rpt -pb interactive_score_utilization_synth.pb }
